// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Githubenterprise struct {
	InstanceUrl string `mapstructure:"instance-url"`
	Token string `mapstructure:"token"`
	Orgs []string `mapstructure:"orgs"`
	AppId string `mapstructure:"app-id"`
	AppPrivatekeyPath []byte `mapstructure:"app-privatekey-path"`
	Org string `mapstructure:"org"`
	Enterprises []string `mapstructure:"enterprises"`
	SyncSecrets bool `mapstructure:"sync-secrets"`
	OmitArchivedRepositories bool `mapstructure:"omit-archived-repositories"`
}

func (c *Githubenterprise) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Githubenterprise) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Githubenterprise) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *Githubenterprise) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Githubenterprise) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Githubenterprise) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
