name: ci
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BATON_TOKEN: ${{ secrets.BATON_TOKEN }}
      BATON_ENTERPRISES: mevans-test
      BATON_ORGS: mevans-test-org1
      BATON_INSTANCE_URL: https://github.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-github-enterprise
        run: go build ./cmd/baton-github-enterprise
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-github-enterprise
          baton-entitlement: 'org_role:8132:assigned'
          baton-principal: '268751836'
          baton-principal-type: 'user'
